# Generated by Django 3.2.6 on 2023-08-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20230806_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
