# Generated by Django 3.2.6 on 2023-08-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_remove_useractivity_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
