# Generated by Django 3.2.6 on 2023-08-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_useractivity_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
